# Generated by Django 5.2.12 on 2026-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=32)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('schema', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('preview_columns', models.JSONField(default=list)),
                ('processing_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
