# Generated by Django 5.2.12 on 2026-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingrun",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="engine",
            field=models.CharField(choices=[("pandas", "Pandas"), ("spark", "Spark")], default="pandas", max_length=16),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="preview_page",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="preview_rows",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="progress_stage",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="processingrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
