# Generated by Django 5.2.12 on 2026-05-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_processingrun_async_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingrun',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='processingrun',
            name='comparison_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='run_type',
            field=models.CharField(choices=[('process', 'Process'), ('spark_compare', 'Spark Compare')], default='process', max_length=32),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_processing.processingrun'),
        ),
    ]
