"""Add indexes used by the optimized tracked-run query paths."""

# Generated by Django 5.2.12 on 2026-06-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0003_alter_processingrun_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['object_key', 'created_at'], name='dproc_object_created_idx'),
        ),
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['status', 'created_at'], name='dproc_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['run_type', 'created_at'], name='dproc_runtype_created_idx'),
        ),
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['source_run', 'created_at'], name='dproc_source_created_idx'),
        ),
    ]
